//HintName: Sample.Nested.Deep.Outer.Machine.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample.Nested.Deep
{
    public partial class Outer
    {
        internal partial class Machine
        {
            public enum State
            {
                A,
                B,
            }
            
            public enum Trigger
            {
                Go,
            }
            
            protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Nested.Deep.Ctx, State, Trigger>
            {
            }
            
            protected interface IStateConfigurator : IStateConfiguration
            {
                IStateConfigurator OnEntry(Action<global::Sample.Nested.Deep.Ctx> action);
                IStateConfigurator OnExit(Action<global::Sample.Nested.Deep.Ctx> action);
                IStateConfigurator OnGo(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State>> configure);
            }
            
            protected static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
            
            private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, State, Trigger> _definition = BuildDefinition();
            
            private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, State, Trigger> BuildDefinition()
            {
                var map = new Dictionary<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Nested.Deep.Ctx, State, Trigger>>();
                {
                    var c = (GeneratedStateConfigurator)A;
                    map[State.A] = c;
                }
                {
                    var c = (GeneratedStateConfigurator)B;
                    map[State.B] = c;
                }
                return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, State, Trigger>(map);
            }
            
            public static Actor CreateActor(State currentState, global::Sample.Nested.Deep.Ctx context) => new Actor(_definition, currentState, context);
            
            public sealed class Actor
            {
                private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Nested.Deep.Ctx, State, Trigger> _engine;
                
                internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, State, Trigger> definition, State currentState, global::Sample.Nested.Deep.Ctx context)
                {
                    _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Nested.Deep.Ctx, State, Trigger>(definition, currentState, context);
                }
                
                public State CurrentState => _engine.CurrentState;
                
                public global::Sample.Nested.Deep.Ctx Context => _engine.Context;
                
                public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled
                {
                    get => _engine.OnUnhandled;
                    set => _engine.OnUnhandled = value;
                }
                
                public event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged
                {
                    add => _engine.StateChanged += value;
                    remove => _engine.StateChanged -= value;
                }
                
                public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed
                {
                    add => _engine.ReactionFailed += value;
                    remove => _engine.ReactionFailed -= value;
                }
                
                public bool IsIn(State state) => _engine.IsIn(state);
                
                public void Go() => _engine.Fire(Trigger.Go, global::Nalu.SharpState.TriggerArgs.Empty);
            }
            
            private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Nested.Deep.Ctx, State, Trigger>, IStateConfigurator
            {
                internal void ApplyParent(State parent) => SetParent(parent);
                
                internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
                
                public IStateConfigurator OnEntry(Action<global::Sample.Nested.Deep.Ctx> action)
                {
                    SetEntryAction(action);
                    return this;
                }
                
                public IStateConfigurator OnExit(Action<global::Sample.Nested.Deep.Ctx> action)
                {
                    SetExitAction(action);
                    return this;
                }
                
                public IStateConfigurator OnGo(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State>> configure)
                {
                    var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State>();
                    configure(builder);
                    builder.Validate();
                    AddTransitions(Trigger.Go, builder.BuildTransitions());
                    return this;
                }
            }
        }
    }
}
