//HintName: Sample.Hier.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample
{
    public partial class Hier
    {
        public enum State
        {
            Idle,
            Connected,
            Authenticating,
            Authenticated,
        }
        
        public enum Trigger
        {
            Connect,
            Disconnect,
            AuthOk,
            Message,
        }
        
        protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger, IActor>
        {
        }
        
        protected interface IStateConfigurator : IStateConfiguration
        {
            /// <summary>
            /// Declares a synchronous callback to run after the machine enters this state.
            /// See <see cref="global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, State, Trigger, IActor>.SetEntryAction(Action<global::Sample.Ctx>)"/>.
            /// </summary>
            /// <param name="action">The callback to run after the state is entered.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator WhenEntering(Action<global::Sample.Ctx> action);
            
            /// <summary>
            /// Declares a synchronous callback to run before the machine exits this state.
            /// See <see cref="global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, State, Trigger, IActor>.SetExitAction(Action<global::Sample.Ctx>)"/>.
            /// </summary>
            /// <param name="action">The callback to run before the state is exited.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator WhenExiting(Action<global::Sample.Ctx> action);
            
            /// <summary>
            /// Configures what happens when <see cref="IActor.Connect()"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>"/> used by <see cref="IActor.Connect()"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnConnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure);
            
            /// <summary>
            /// Configures what happens when <see cref="IActor.Disconnect()"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>"/> used by <see cref="IActor.Disconnect()"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnDisconnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure);
            
            /// <summary>
            /// Configures what happens when <see cref="IActor.AuthOk()"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>"/> used by <see cref="IActor.AuthOk()"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnAuthOk(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure);
            
            /// <summary>
            /// Configures what happens when <see cref="IActor.Message(string)"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, string>"/> used by <see cref="IActor.Message(string)"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnMessage(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, string>> configure);
        }
        
        /// <summary>
        /// <see cref="global::Sample.Hier"/> runtime actor.
        /// </summary>
        /// <remarks>
        /// Use <see cref="CreateActor(State, global::Sample.Ctx)"/> to create an instance.
        /// </remarks>
        public interface IActor
        {
            /// <summary>
            /// Gets the current leaf <see cref="State"/>.
            /// </summary>
            State CurrentState { get; }
            
            /// <summary>
            /// Gets the shared context passed to guards, actions, and reactions.
            /// </summary>
            global::Sample.Ctx Context { get; }
            
            /// <summary>
            /// Gets or sets the callback invoked when a trigger has no matching transition.
            /// </summary>
            global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled { get; set; }
            
            /// <summary>
            /// Raised after a transition commits and changes the current state.
            /// </summary>
            event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged;
            
            /// <summary>
            /// Raised when a background reaction scheduled by <c>ReactAsync(...)</c> fails.
            /// </summary>
            event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed;
            
            /// <summary>
            /// Determines whether the current leaf equals <paramref name="state"/> or is contained by it.
            /// </summary>
            /// <param name="state">The state to test against the current hierarchy.</param>
            /// <returns><c>true</c> when the actor is currently in <paramref name="state"/>; otherwise <c>false</c>.</returns>
            bool IsIn(State state);
            
            /// <summary>
            /// Fires <see cref="Trigger.Connect"/> from the current state.
            /// </summary>
            void Connect();
            
            /// <summary>
            /// Fires <see cref="Trigger.Disconnect"/> from the current state.
            /// </summary>
            void Disconnect();
            
            /// <summary>
            /// Fires <see cref="Trigger.AuthOk"/> from the current state.
            /// </summary>
            void AuthOk();
            
            /// <summary>
            /// Fires <see cref="Trigger.Message"/> from the current state.
            /// </summary>
            /// <param name="m">The value to pass to the trigger.</param>
            void Message(string m);
        }
        
        protected static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
        
        private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger, IActor> _definition = BuildDefinition();
        
        private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger, IActor> BuildDefinition()
        {
            var map = new Dictionary<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger, IActor>>();
            {
                var c = (GeneratedStateConfigurator)Idle;
                map[State.Idle] = c;
            }
            {
                var c = (GeneratedStateConfigurator)Connected;
                c.ApplyInitialChild(State.Authenticating);
                map[State.Connected] = c;
            }
            ConnectedRegion.__Register(map);
            return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger, IActor>(map);
        }
        
        /// <summary>
        /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
        /// </summary>
        /// <param name="currentState">The starting state. Composite states resolve to their initial leaf.</param>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public static IActor CreateActor(State currentState, global::Sample.Ctx context) => new Actor(_definition, currentState, context);
        
        private sealed class Actor : IActor
        {
            private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, State, Trigger, IActor> _engine;
            
            internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger, IActor> definition, State currentState, global::Sample.Ctx context)
            {
                _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, State, Trigger, IActor>(definition, currentState, context, this);
            }
            
            public State CurrentState => _engine.CurrentState;
            
            public global::Sample.Ctx Context => _engine.Context;
            
            public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled
            {
                get => _engine.OnUnhandled;
                set => _engine.OnUnhandled = value;
            }
            
            public event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged
            {
                add => _engine.StateChanged += value;
                remove => _engine.StateChanged -= value;
            }
            
            public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed
            {
                add => _engine.ReactionFailed += value;
                remove => _engine.ReactionFailed -= value;
            }
            
            public bool IsIn(State state) => _engine.IsIn(state);
            
            public void Connect() => _engine.Fire(Trigger.Connect, global::Nalu.SharpState.TriggerArgs.Empty);
            
            public void Disconnect() => _engine.Fire(Trigger.Disconnect, global::Nalu.SharpState.TriggerArgs.Empty);
            
            public void AuthOk() => _engine.Fire(Trigger.AuthOk, global::Nalu.SharpState.TriggerArgs.Empty);
            
            public void Message(string m) => _engine.Fire(Trigger.Message, global::Nalu.SharpState.TriggerArgs.From(m));
        }
        
        private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, State, Trigger, IActor>, IStateConfigurator
        {
            internal void ApplyParent(State parent) => SetParent(parent);
            
            internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
            
            public IStateConfigurator WhenEntering(Action<global::Sample.Ctx> action)
            {
                SetEntryAction(action);
                return this;
            }
            
            public IStateConfigurator WhenExiting(Action<global::Sample.Ctx> action)
            {
                SetExitAction(action);
                return this;
            }
            
            public IStateConfigurator OnConnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State, IActor>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Connect, builder.BuildTransitions());
                return this;
            }
            
            public IStateConfigurator OnDisconnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State, IActor>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Disconnect, builder.BuildTransitions());
                return this;
            }
            
            public IStateConfigurator OnAuthOk(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State, IActor>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.AuthOk, builder.BuildTransitions());
                return this;
            }
            
            public IStateConfigurator OnMessage(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, string>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State, IActor, string>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Message, builder.BuildTransitions());
                return this;
            }
        }
        
        partial class ConnectedRegion
        {
            internal static void __Register(global::System.Collections.Generic.Dictionary<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger, IActor>> map)
            {
                {
                    var c = (GeneratedStateConfigurator)Authenticating;
                    c.ApplyParent(State.Connected);
                    map[State.Authenticating] = c;
                }
                {
                    var c = (GeneratedStateConfigurator)Authenticated;
                    c.ApplyParent(State.Connected);
                    map[State.Authenticated] = c;
                }
            }
        }
    }
}
