//HintName: Sample.ReactionMachine.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample
{
    public partial class ReactionMachine
    {
        public enum State
        {
            Idle,
            Running,
        }
        
        public enum Trigger
        {
            Start,
            Sync,
        }
        
        protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger, IActor>
        {
        }
        
        protected interface IStateConfigurator : IStateConfiguration
        {
            /// <summary>
            /// Declares a synchronous callback to run after the machine enters this state.
            /// See <see cref="global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, State, Trigger, IActor>.SetEntryAction(Action<global::Sample.Ctx>)"/>.
            /// </summary>
            /// <param name="action">The callback to run after the state is entered.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator WhenEntering(Action<global::Sample.Ctx> action);
            
            /// <summary>
            /// Declares a synchronous callback to run before the machine exits this state.
            /// See <see cref="global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, State, Trigger, IActor>.SetExitAction(Action<global::Sample.Ctx>)"/>.
            /// </summary>
            /// <param name="action">The callback to run before the state is exited.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator WhenExiting(Action<global::Sample.Ctx> action);
            
            /// <summary>
            /// Configures what happens when <see cref="IActor.Start()"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>"/> used by <see cref="IActor.Start()"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnStart(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure);
            
            /// <summary>
            /// Configures what happens when <see cref="IActor.Sync(long)"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, long>"/> used by <see cref="IActor.Sync(long)"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnSync(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, long>> configure);
        }
        
        /// <summary>
        /// <see cref="global::Sample.ReactionMachine"/> runtime actor.
        /// </summary>
        /// <remarks>
        /// Use <see cref="CreateActor(State, global::Sample.Ctx)"/> to create an instance.
        /// </remarks>
        public interface IActor
        {
            /// <summary>
            /// Gets the current leaf <see cref="State"/>.
            /// </summary>
            State CurrentState { get; }
            
            /// <summary>
            /// Gets the shared context passed to guards, actions, and reactions.
            /// </summary>
            global::Sample.Ctx Context { get; }
            
            /// <summary>
            /// Gets or sets the callback invoked when a trigger has no matching transition.
            /// </summary>
            global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled { get; set; }
            
            /// <summary>
            /// Raised after a transition commits and changes the current state.
            /// </summary>
            event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged;
            
            /// <summary>
            /// Raised when a background reaction scheduled by <c>ReactAsync(...)</c> fails.
            /// </summary>
            event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed;
            
            /// <summary>
            /// Determines whether the current leaf equals <paramref name="state"/> or is contained by it.
            /// </summary>
            /// <param name="state">The state to test against the current hierarchy.</param>
            /// <returns><c>true</c> when the actor is currently in <paramref name="state"/>; otherwise <c>false</c>.</returns>
            bool IsIn(State state);
            
            /// <summary>
            /// Fires <see cref="Trigger.Start"/> from the current state.
            /// </summary>
            void Start();
            
            /// <summary>
            /// Fires <see cref="Trigger.Sync"/> from the current state.
            /// </summary>
            /// <param name="revision">The value to pass to the trigger.</param>
            void Sync(long revision);
        }
        
        /// <summary>
        /// Factory delegate that creates a new <see cref="IActor"/> bound to this generated state machine definition.
        /// Useful for dependency injection and unit tests.
        /// </summary>
        /// <param name="currentState">The starting state. Composite states resolve to their initial leaf.</param>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public delegate IActor Factory(State currentState, global::Sample.Ctx context);
        
        protected static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
        
        private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger, IActor> _definition = BuildDefinition();
        
        private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger, IActor> BuildDefinition()
        {
            var map = new Dictionary<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger, IActor>>();
            {
                var c = (GeneratedStateConfigurator)Idle;
                map[State.Idle] = c;
            }
            {
                var c = (GeneratedStateConfigurator)Running;
                map[State.Running] = c;
            }
            return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger, IActor>(map);
        }
        
        /// <summary>
        /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
        /// </summary>
        /// <param name="currentState">The starting state. Composite states resolve to their initial leaf.</param>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public static IActor CreateActor(State currentState, global::Sample.Ctx context) => new Actor(_definition, currentState, context);
        
        private sealed class Actor : IActor
        {
            private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, State, Trigger, IActor> _engine;
            
            internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger, IActor> definition, State currentState, global::Sample.Ctx context)
            {
                _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, State, Trigger, IActor>(definition, currentState, context, this);
            }
            
            public State CurrentState => _engine.CurrentState;
            
            public global::Sample.Ctx Context => _engine.Context;
            
            public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled
            {
                get => _engine.OnUnhandled;
                set => _engine.OnUnhandled = value;
            }
            
            public event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged
            {
                add => _engine.StateChanged += value;
                remove => _engine.StateChanged -= value;
            }
            
            public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed
            {
                add => _engine.ReactionFailed += value;
                remove => _engine.ReactionFailed -= value;
            }
            
            public bool IsIn(State state) => _engine.IsIn(state);
            
            public void Start() => _engine.Fire(Trigger.Start, global::Nalu.SharpState.TriggerArgs.Empty);
            
            public void Sync(long revision) => _engine.Fire(Trigger.Sync, global::Nalu.SharpState.TriggerArgs.From(revision));
        }
        
        private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, State, Trigger, IActor>, IStateConfigurator
        {
            internal void ApplyParent(State parent) => SetParent(parent);
            
            internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
            
            public IStateConfigurator WhenEntering(Action<global::Sample.Ctx> action)
            {
                SetEntryAction(action);
                return this;
            }
            
            public IStateConfigurator WhenExiting(Action<global::Sample.Ctx> action)
            {
                SetExitAction(action);
                return this;
            }
            
            public IStateConfigurator OnStart(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State, IActor>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Start, builder.BuildTransitions());
                return this;
            }
            
            public IStateConfigurator OnSync(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, long>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State, IActor, long>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Sync, builder.BuildTransitions());
                return this;
            }
        }
    }
}
