//HintName: Sample.Flat.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample
{
    public partial class Flat
    {
        public enum State
        {
            Idle,
            Connected,
        }
        
        public enum Trigger
        {
            Connect,
            Disconnect,
        }
        
        protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger>
        {
        }
        
        protected interface IStateConfigurator : IStateConfiguration
        {
            IStateConfigurator WhenEntering(Action<global::Sample.Ctx> action);
            IStateConfigurator WhenExiting(Action<global::Sample.Ctx> action);
            IStateConfigurator OnConnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, string>> configure);
            IStateConfigurator OnDisconnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State>> configure);
        }
        
        protected static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
        
        private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger> _definition = BuildDefinition();
        
        private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger> BuildDefinition()
        {
            var map = new Dictionary<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger>>();
            {
                var c = (GeneratedStateConfigurator)Idle;
                map[State.Idle] = c;
            }
            {
                var c = (GeneratedStateConfigurator)Connected;
                map[State.Connected] = c;
            }
            return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger>(map);
        }
        
        public static Actor CreateActor(State currentState, global::Sample.Ctx context) => new Actor(_definition, currentState, context);
        
        public sealed class Actor
        {
            private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, State, Trigger> _engine;
            
            internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger> definition, State currentState, global::Sample.Ctx context)
            {
                _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, State, Trigger>(definition, currentState, context);
            }
            
            public State CurrentState => _engine.CurrentState;
            
            public global::Sample.Ctx Context => _engine.Context;
            
            public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled
            {
                get => _engine.OnUnhandled;
                set => _engine.OnUnhandled = value;
            }
            
            public event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged
            {
                add => _engine.StateChanged += value;
                remove => _engine.StateChanged -= value;
            }
            
            public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed
            {
                add => _engine.ReactionFailed += value;
                remove => _engine.ReactionFailed -= value;
            }
            
            public bool IsIn(State state) => _engine.IsIn(state);
            
            public void Connect(string deviceId) => _engine.Fire(Trigger.Connect, global::Nalu.SharpState.TriggerArgs.From(deviceId));
            
            public void Disconnect() => _engine.Fire(Trigger.Disconnect, global::Nalu.SharpState.TriggerArgs.Empty);
        }
        
        private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, State, Trigger>, IStateConfigurator
        {
            internal void ApplyParent(State parent) => SetParent(parent);
            
            internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
            
            public IStateConfigurator WhenEntering(Action<global::Sample.Ctx> action)
            {
                SetEntryAction(action);
                return this;
            }
            
            public IStateConfigurator WhenExiting(Action<global::Sample.Ctx> action)
            {
                SetExitAction(action);
                return this;
            }
            
            public IStateConfigurator OnConnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, string>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State, string>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Connect, builder.BuildTransitions());
                return this;
            }
            
            public IStateConfigurator OnDisconnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Disconnect, builder.BuildTransitions());
                return this;
            }
        }
    }
}
