//HintName: Sample.Hooks.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample
{
    public partial class Hooks
    {
        public enum State
        {
            Idle,
            Running,
        }
        
        public enum Trigger
        {
            Start,
            Ping,
        }
        
        protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger>
        {
        }
        
        protected interface IStateConfigurator : IStateConfiguration
        {
            IStateConfigurator OnEntry(Action<global::Sample.Ctx> action);
            IStateConfigurator OnExit(Action<global::Sample.Ctx> action);
            IStateConfigurator OnStart(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State>> configure);
            IStateConfigurator OnPing(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State>> configure);
        }
        
        protected static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
        
        private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger> _definition = BuildDefinition();
        
        private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger> BuildDefinition()
        {
            var map = new Dictionary<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, State, Trigger>>();
            {
                var c = (GeneratedStateConfigurator)Idle;
                map[State.Idle] = c;
            }
            {
                var c = (GeneratedStateConfigurator)Running;
                map[State.Running] = c;
            }
            return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger>(map);
        }
        
        public static Actor CreateActor(State currentState, global::Sample.Ctx context) => new Actor(_definition, currentState, context);
        
        public sealed class Actor
        {
            private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, State, Trigger> _engine;
            
            internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, State, Trigger> definition, State currentState, global::Sample.Ctx context)
            {
                _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, State, Trigger>(definition, currentState, context);
            }
            
            public State CurrentState => _engine.CurrentState;
            
            public global::Sample.Ctx Context => _engine.Context;
            
            public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled
            {
                get => _engine.OnUnhandled;
                set => _engine.OnUnhandled = value;
            }
            
            public event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged
            {
                add => _engine.StateChanged += value;
                remove => _engine.StateChanged -= value;
            }
            
            public bool IsIn(State state) => _engine.IsIn(state);
            
            public void Start() => _engine.Fire(Trigger.Start, global::Nalu.SharpState.TriggerArgs.Empty);
            
            public void Ping() => _engine.Fire(Trigger.Ping, global::Nalu.SharpState.TriggerArgs.Empty);
        }
        
        private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, State, Trigger>, IStateConfigurator
        {
            internal void ApplyParent(State parent) => SetParent(parent);
            
            internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
            
            public IStateConfigurator OnEntry(Action<global::Sample.Ctx> action)
            {
                SetEntryAction(action);
                return this;
            }
            
            public IStateConfigurator OnExit(Action<global::Sample.Ctx> action)
            {
                SetExitAction(action);
                return this;
            }
            
            public IStateConfigurator OnStart(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Start, builder.BuildTransitions());
                return this;
            }
            
            public IStateConfigurator OnPing(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, State>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Ping, builder.BuildTransitions());
                return this;
            }
        }
    }
}
