//HintName: Sample.Nested.Deep.Outer.Machine.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample.Nested.Deep
{
    public partial class Outer
    {
        internal partial class Machine
        {
            public enum State
            {
                A,
                B,
            }
            
            public enum Trigger
            {
                Go,
            }
            
            protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor>
            {
            }
            
            protected interface IStateConfigurator : IStateConfiguration
            {
                /// <summary>
                /// Declares a synchronous callback to run after the machine enters this state.
                /// See <see cref="global::Nalu.SharpState.StateConfigurator<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor>.SetEntryAction(Action<global::Sample.Nested.Deep.Ctx>)"/>.
                /// </summary>
                /// <param name="action">The callback to run after the state is entered.</param>
                /// <returns>The same configurator for chaining.</returns>
                IStateConfigurator WhenEntering(Action<global::Sample.Nested.Deep.Ctx> action);
                
                /// <summary>
                /// Declares a synchronous callback to run before the machine exits this state.
                /// See <see cref="global::Nalu.SharpState.StateConfigurator<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor>.SetExitAction(Action<global::Sample.Nested.Deep.Ctx>)"/>.
                /// </summary>
                /// <param name="action">The callback to run before the state is exited.</param>
                /// <returns>The same configurator for chaining.</returns>
                IStateConfigurator WhenExiting(Action<global::Sample.Nested.Deep.Ctx> action);
                
                /// <summary>
                /// Configures what happens when <see cref="IActor.Go()"/> is invoked.
                /// </summary>
                /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State, IActor>"/> used by <see cref="IActor.Go()"/>.</param>
                /// <returns>The same configurator for chaining.</returns>
                IStateConfigurator OnGo(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State, IActor>> configure);
            }
            
            /// <summary>
            /// <see cref="global::Sample.Nested.Deep.Outer.Machine"/> runtime actor.
            /// </summary>
            /// <remarks>
            /// Use <see cref="CreateActor(State, global::Sample.Nested.Deep.Ctx)"/> to create an instance.
            /// </remarks>
            public interface IActor
            {
                /// <summary>
                /// Gets the current leaf <see cref="State"/>.
                /// </summary>
                State CurrentState { get; }
                
                /// <summary>
                /// Gets the shared context passed to guards, actions, and reactions.
                /// </summary>
                global::Sample.Nested.Deep.Ctx Context { get; }
                
                /// <summary>
                /// Gets or sets the callback invoked when a trigger has no matching transition.
                /// </summary>
                global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled { get; set; }
                
                /// <summary>
                /// Raised after a transition commits and changes the current state.
                /// </summary>
                event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged;
                
                /// <summary>
                /// Raised when a background reaction scheduled by <c>ReactAsync(...)</c> fails.
                /// </summary>
                event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed;
                
                /// <summary>
                /// Determines whether the current leaf equals <paramref name="state"/> or is contained by it.
                /// </summary>
                /// <param name="state">The state to test against the current hierarchy.</param>
                /// <returns><c>true</c> when the actor is currently in <paramref name="state"/>; otherwise <c>false</c>.</returns>
                bool IsIn(State state);
                
                /// <summary>
                /// Fires <see cref="Trigger.Go"/> from the current state.
                /// </summary>
                void Go();
            }
            
            protected static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
            
            private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor> _definition = BuildDefinition();
            
            private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor> BuildDefinition()
            {
                var map = new Dictionary<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor>>();
                {
                    var c = (GeneratedStateConfigurator)A;
                    map[State.A] = c;
                }
                {
                    var c = (GeneratedStateConfigurator)B;
                    map[State.B] = c;
                }
                return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor>(map);
            }
            
            /// <summary>
            /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
            /// </summary>
            /// <param name="currentState">The starting state. Composite states resolve to their initial leaf.</param>
            /// <param name="context">The shared <see cref="global::Sample.Nested.Deep.Ctx"/> passed to guards, actions, and reactions.</param>
            /// <returns>A new <see cref="IActor"/> instance.</returns>
            public static IActor CreateActor(State currentState, global::Sample.Nested.Deep.Ctx context) => new Actor(_definition, currentState, context);
            
            private sealed class Actor : IActor
            {
                private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor> _engine;
                
                internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor> definition, State currentState, global::Sample.Nested.Deep.Ctx context)
                {
                    _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor>(definition, currentState, context, this);
                }
                
                public State CurrentState => _engine.CurrentState;
                
                public global::Sample.Nested.Deep.Ctx Context => _engine.Context;
                
                public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled
                {
                    get => _engine.OnUnhandled;
                    set => _engine.OnUnhandled = value;
                }
                
                public event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged
                {
                    add => _engine.StateChanged += value;
                    remove => _engine.StateChanged -= value;
                }
                
                public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed
                {
                    add => _engine.ReactionFailed += value;
                    remove => _engine.ReactionFailed -= value;
                }
                
                public bool IsIn(State state) => _engine.IsIn(state);
                
                public void Go() => _engine.Fire(Trigger.Go, global::Nalu.SharpState.TriggerArgs.Empty);
            }
            
            private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Nested.Deep.Ctx, State, Trigger, IActor>, IStateConfigurator
            {
                internal void ApplyParent(State parent) => SetParent(parent);
                
                internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
                
                public IStateConfigurator WhenEntering(Action<global::Sample.Nested.Deep.Ctx> action)
                {
                    SetEntryAction(action);
                    return this;
                }
                
                public IStateConfigurator WhenExiting(Action<global::Sample.Nested.Deep.Ctx> action)
                {
                    SetExitAction(action);
                    return this;
                }
                
                public IStateConfigurator OnGo(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State, IActor>> configure)
                {
                    var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State, IActor>();
                    configure(builder);
                    builder.Validate();
                    AddTransitions(Trigger.Go, builder.BuildTransitions());
                    return this;
                }
            }
        }
    }
}
