<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Source\Nalu.Maui.Scaffold.SourceGenerators\Nalu.Maui.Scaffold.SourceGenerators.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
      <PackageReference Include="FluentAssertions" Version="8.8.0" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
      <PackageReference Include="xunit.v3" Version="3.2.1" />
      <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>
