//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nalu.Maui.Weather.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nalu.Maui.Weather.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoadingIQ {
            get {
                return ResourceManager.GetString("LoadingIQ", resourceCulture);
            }
        }
        
        internal static string LoadingWeatherForecast {
            get {
                return ResourceManager.GetString("LoadingWeatherForecast", resourceCulture);
            }
        }
        
        internal static string GettingLocation {
            get {
                return ResourceManager.GetString("GettingLocation", resourceCulture);
            }
        }
        
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        internal static string AirQuality {
            get {
                return ResourceManager.GetString("AirQuality", resourceCulture);
            }
        }
        
        internal static string WeatherForecast {
            get {
                return ResourceManager.GetString("WeatherForecast", resourceCulture);
            }
        }
        
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        internal static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        internal static string PM10 {
            get {
                return ResourceManager.GetString("PM10", resourceCulture);
            }
        }
        
        internal static string PM25 {
            get {
                return ResourceManager.GetString("PM25", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
