using Microsoft.CodeAnalysis;
using Nalu.SharpState.Generators.Model;

namespace Nalu.SharpState.Generators.Emit;

/// <summary>
/// Turns a <see cref="StateMachineModel"/> into the generated <c>.g.cs</c> source text and reports any
/// diagnostics accumulated during model extraction.
/// </summary>
internal static class StateMachineEmitter
{
    public static void Emit(SourceProductionContext context, StateMachineModel model)
    {
        foreach (var diagnostic in model.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (model.Diagnostics.Any(d => d.Descriptor.DefaultSeverity == DiagnosticSeverity.Error))
        {
            return;
        }

        var writer = new SourceWriter();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("#pragma warning disable CS1591");
        writer.WriteBlankLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using global::Nalu.SharpState;");
        writer.WriteBlankLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            writer.WriteLine($"namespace {model.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        foreach (var containing in model.ContainingTypes)
        {
            writer.WriteLine($"{containing.Accessibility} partial {containing.Keyword} {containing.Name}{containing.TypeParameters}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        EmitMachineBody(writer, model);

        for (var i = 0; i < model.ContainingTypes.Count; i++)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        if (hasNamespace)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        context.AddSource(SanitizeHintName(model.Hintname), writer.ToString());
    }

    private static string SanitizeHintName(string hint) => hint.Replace('/', '.').Replace('\\', '.');

    private static void EmitMachineBody(SourceWriter w, StateMachineModel m)
    {
        var context = m.ContextTypeDisplay;
        var className = m.ClassName;
        var typeParams = m.TypeParameters;

        w.WriteLine($"{m.ClassAccessibility} partial {m.ClassKeyword} {className}{typeParams}");
        using (w.Block())
        {
            EmitStateEnum(w, m);
            w.WriteBlankLine();
            EmitTriggerEnum(w, m);
            w.WriteBlankLine();
            EmitConfigurationInterface(w, context);
            w.WriteBlankLine();
            EmitConfiguratorInterface(w, context, m);
            w.WriteBlankLine();
            w.WriteLine("protected static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();");
            w.WriteBlankLine();
            w.WriteLine($"private static readonly global::Nalu.SharpState.StateMachineDefinition<{context}, State, Trigger> _definition = BuildDefinition();");
            w.WriteBlankLine();
            EmitBuildDefinition(w, context, m);
            w.WriteBlankLine();
            w.WriteLine($"public static Actor CreateActor(State currentState, {context} context) => new Actor(_definition, currentState, context);");
            w.WriteBlankLine();
            EmitActorClass(w, context, m);
            w.WriteBlankLine();
            EmitGeneratedConfigurator(w, context, m);
            EmitRegionRegistrars(w, context, m);
        }
    }

    private static RegionNode BuildRegionTree(StateMachineModel m)
    {
        var root = new RegionNode(string.Empty);
        foreach (var s in m.States)
        {
            var node = root;
            if (!string.IsNullOrEmpty(s.RegionPath))
            {
                foreach (var seg in s.RegionPath.Split('.'))
                {
                    if (!node.Children.TryGetValue(seg, out var next))
                    {
                        next = new RegionNode(seg);
                        node.Children[seg] = next;
                    }
                    node = next;
                }
            }

            node.States.Add(s);
        }

        return root;
    }

    private static void EmitRegionRegistrars(SourceWriter w, string context, StateMachineModel m)
    {
        var root = BuildRegionTree(m);
        foreach (var top in root.Children.Values)
        {
            w.WriteBlankLine();
            EmitRegionClass(w, context, top);
        }
    }

    private static void EmitRegionClass(SourceWriter w, string context, RegionNode node)
    {
        w.WriteLine($"partial class {node.Name}");
        using (w.Block())
        {
            w.WriteLine(
                $"internal static void __Register(global::System.Collections.Generic.Dictionary<State, global::Nalu.SharpState.IStateConfiguration<{context}, State, Trigger>> map)");
            using (w.Block())
            {
                foreach (var s in node.States)
                {
                    EmitStateRegistration(w, s);
                }

                foreach (var child in node.Children.Values)
                {
                    w.WriteLine($"{child.Name}.__Register(map);");
                }
            }

            foreach (var child in node.Children.Values)
            {
                w.WriteBlankLine();
                EmitRegionClass(w, context, child);
            }
        }
    }

    private static void EmitStateRegistration(SourceWriter w, StateModel s)
    {
        using (w.Block())
        {
            w.WriteLine($"var c = (GeneratedStateConfigurator){s.Name};");
            if (s.ParentState is not null)
            {
                w.WriteLine($"c.ApplyParent(State.{s.ParentState});");
            }
            if (s.InitialChildState is not null)
            {
                w.WriteLine($"c.ApplyInitialChild(State.{s.InitialChildState});");
            }
            w.WriteLine($"map[State.{s.Name}] = c;");
        }
    }

    private sealed class RegionNode
    {
        public RegionNode(string name)
        {
            Name = name;
        }

        public string Name { get; }
        public SortedDictionary<string, RegionNode> Children { get; } = new(StringComparer.Ordinal);
        public List<StateModel> States { get; } = new();
    }

    private static void EmitStateEnum(SourceWriter w, StateMachineModel m)
    {
        w.WriteLine("public enum State");
        using (w.Block())
        {
            foreach (var s in m.States)
            {
                w.WriteLine($"{s.Name},");
            }
        }
    }

    private static void EmitTriggerEnum(SourceWriter w, StateMachineModel m)
    {
        w.WriteLine("public enum Trigger");
        using (w.Block())
        {
            foreach (var t in m.Triggers)
            {
                w.WriteLine($"{t.Name},");
            }
        }
    }

    private static void EmitConfigurationInterface(SourceWriter w, string context)
    {
        w.WriteLine($"protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<{context}, State, Trigger>");
        using (w.Block())
        { }
    }

    private static void EmitConfiguratorInterface(SourceWriter w, string context, StateMachineModel m)
    {
        w.WriteLine("protected interface IStateConfigurator : IStateConfiguration");
        using (w.Block())
        {
            foreach (var t in m.Triggers)
            {
                w.WriteLine($"IStateConfigurator On{t.Name}(Action<{BuilderInterfaceType(context, t, m.IsAsync)}> configure);");
            }
        }
    }

    private static void EmitBuildDefinition(SourceWriter w, string context, StateMachineModel m)
    {
        w.WriteLine($"private static global::Nalu.SharpState.StateMachineDefinition<{context}, State, Trigger> BuildDefinition()");
        using (w.Block())
        {
            w.WriteLine($"var map = new Dictionary<State, global::Nalu.SharpState.IStateConfiguration<{context}, State, Trigger>>();");

            var root = BuildRegionTree(m);
            foreach (var s in root.States)
            {
                EmitStateRegistration(w, s);
            }

            foreach (var child in root.Children.Values)
            {
                w.WriteLine($"{child.Name}.__Register(map);");
            }

            w.WriteLine($"return new global::Nalu.SharpState.StateMachineDefinition<{context}, State, Trigger>(map);");
        }
    }

    private static void EmitActorClass(SourceWriter w, string context, StateMachineModel m)
    {
        w.WriteLine("public sealed class Actor");
        using (w.Block())
        {
            w.WriteLine($"private readonly global::Nalu.SharpState.StateMachineEngine<{context}, State, Trigger> _engine;");
            w.WriteBlankLine();
            w.WriteLine(
                $"internal Actor(global::Nalu.SharpState.StateMachineDefinition<{context}, State, Trigger> definition, State currentState, {context} context)");
            using (w.Block())
            {
                w.WriteLine(
                    $"_engine = new global::Nalu.SharpState.StateMachineEngine<{context}, State, Trigger>(definition, currentState, context);");
            }

            w.WriteBlankLine();
            w.WriteLine("public State CurrentState => _engine.CurrentState;");
            w.WriteBlankLine();
            w.WriteLine($"public {context} Context => _engine.Context;");
            w.WriteBlankLine();
            w.WriteLine("public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled");
            using (w.Block())
            {
                w.WriteLine("get => _engine.OnUnhandled;");
                w.WriteLine("set => _engine.OnUnhandled = value;");
            }

            w.WriteBlankLine();
            w.WriteLine("public event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged");
            using (w.Block())
            {
                w.WriteLine("add => _engine.StateChanged += value;");
                w.WriteLine("remove => _engine.StateChanged -= value;");
            }

            w.WriteBlankLine();
            w.WriteLine("public bool IsIn(State state) => _engine.IsIn(state);");

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitActorTriggerMethod(w, t, m.IsAsync);
            }
        }
    }

    private static void EmitActorTriggerMethod(SourceWriter w, TriggerModel t, bool isAsync)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        var argArray = t.Parameters.Count == 0
            ? "global::System.Array.Empty<object?>()"
            : "new object?[] { " + string.Join(", ", t.Parameters.Select(p => p.Name)) + " }";

        if (isAsync)
        {
            var methodName = t.Name + "Async";
            w.WriteLine($"public global::System.Threading.Tasks.ValueTask {methodName}({paramList}) => _engine.FireAsync(Trigger.{t.Name}, {argArray});");
        }
        else
        {
            w.WriteLine($"public void {t.Name}({paramList}) => _engine.Fire(Trigger.{t.Name}, {argArray});");
        }
    }

    private static void EmitGeneratedConfigurator(SourceWriter w, string context, StateMachineModel m)
    {
        w.WriteLine(
            $"private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<{context}, State, Trigger>, IStateConfigurator");
        using (w.Block())
        {
            w.WriteLine("internal void ApplyParent(State parent) => SetParent(parent);");
            w.WriteBlankLine();
            w.WriteLine("internal void ApplyInitialChild(State initial) => SetInitialChild(initial);");

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitConfiguratorTriggerMethod(w, context, t, m.IsAsync);
            }
        }
    }

    private static void EmitConfiguratorTriggerMethod(SourceWriter w, string context, TriggerModel t, bool isAsync)
    {
        var builderType = BuilderInterfaceType(context, t, isAsync);
        var concreteBuilder = ConcreteBuilderType(context, t);
        w.WriteLine($"public IStateConfigurator On{t.Name}(Action<{builderType}> configure)");
        using (w.Block())
        {
            w.WriteLine($"var builder = new {concreteBuilder}();");
            w.WriteLine("configure(builder);");
            w.WriteLine("builder.Validate();");
            w.WriteLine($"AddTransitions(Trigger.{t.Name}, builder.BuildTransitions());");
            w.WriteLine("return this;");
        }
    }

    private static string BuilderInterfaceType(string context, TriggerModel t, bool isAsync)
    {
        var kind = isAsync ? "IAsyncStateTriggerBuilder" : "ISyncStateTriggerBuilder";
        if (t.Parameters.Count == 0)
        {
            return $"global::Nalu.SharpState.{kind}<{context}, State>";
        }

        var args = string.Join(", ", t.Parameters.Select(p => p.TypeDisplay));
        return $"global::Nalu.SharpState.{kind}<{context}, State, {args}>";
    }

    private static string ConcreteBuilderType(string context, TriggerModel t)
    {
        if (t.Parameters.Count == 0)
        {
            return $"global::Nalu.SharpState.StateTriggerBuilder<{context}, State>";
        }

        var args = string.Join(", ", t.Parameters.Select(p => p.TypeDisplay));
        return $"global::Nalu.SharpState.StateTriggerBuilder<{context}, State, {args}>";
    }
}
